on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: edited
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            A pull request has been edited 
